### ISSUE TITLE
Ignoring "activate" flag on plugins array

### ISSUE THREAD

**Issue by codepuncher** [JPry/vvv-base#20]
Just stumbled upon this repo and I must say, it's amazing (thanks for your work).

Gave it a go and added some plugins to the config array with `activate: true` and some with `activate: false`. However, it appears that all plugins were activated even though some are set to `false`.

Linux Mint 18.2
Vagrant 1.9.4
VirtualBox 5

This is my vvv-custom.yml contents:

```
---
sites:

  domain:
    repo: https://github.com/JPry/vvv-base.git
    hosts:
      - wp.domain.co.uk
    custom:
      admin_user: lee.hanbury
      admin_password: password
      admin_email: lee@domain.co.uk
      title: Site title
      dp_prefix: cp_
      locale: en_GB
      plugins:
        - { plugin: "duplicate-post", activate: true }
        - { plugin: "http://updates.wpbeaverbuilder.com/?fl-api-method=composer_download&download=bb-plugin-pro.zip&license=xxxx", force: true, activate: true }
        - { plugin: "email-templates", activate: true }
        - { plugin: "gathercontent-import", activate: false }
        - { plugin: "gravityformscli", activate: true }
        - { plugin: "iwp-client", activate: false }
        - { plugin: "password-protected", activate: false }
        - { plugin: "redirection", activate: true }
        - { plugin: "post-expirator", activate: false }
        - { plugin: "postman-smtp", activate: true }
        - { plugin: "regenerate-thumbnails", activate: true }
        - { plugin: "uk-cookie-consent", activate: true }
        - { plugin: "wordfence", activate: false }
        - { plugin: "wordpress-seo", activate: true }
        - { plugin: "wp-nested-pages", activate: false }
        - { plugin: "wp-sentry-integration", activate: false }
        - { plugin: "wp-smushit", activate: true }
        - { plugin: "w3-total-cache", activate: false }
      delete_default_plugins: true
      delete_default_themes: true

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
```
