### ISSUE TITLE
Possibility of extra plugin features?

### ISSUE THREAD

**Issue by codepuncher** [JPry/vvv-base#23]
Being able to list plugins to install and activate is great. But I can see (at least in my case) my `vvv-custom.yml` file growing to a huge size due to having a fairly large list of plugins for each site. All my projects tend to use the same plugins, so I was wondering how possible or easy it would be to be able to sort of "reference" a plugin list to install and activate them?

At the moment I have a repo that has the WP plugins as Composer dependencies which I clone with `htdocs` and manually install the plugins with Composer.

I was thinking that having an option in the config for some sort of "post install" commands would be useful? Or would there be any way to reference a plugin list for each site to install and activate them with WP-CLI? The downside to the Composer way is of course not auto-activating the plugins.

Haven't really seen any other solutions out there for this sort of thing but I think this would be a worthwhile feature, but I don't really know how difficult that would be to do.
I'm happy to help where possible if this could be a feature.

**Comment by JPry** [comment]
That's a really interesting question. It actually *would* be possible to set up a master list of plugins in the  `vvv-custom.yml` file. The beauty of using a YAML file to begin with is that we can set up custom keys that VVV itself doesn't care about at all.

It would certainly be an "advanced" implementation, but a master list of plugins to install with all sites would certainly be doable.

I don't know how soon I can get this integrated, but I'll definitely add it to the feature roadmap.

**Comment by codepuncher** [comment]
Great to hear you're keen on the idea.
With this in place, people can scrap Composer for plugin management.

I assume this would result in a new config option like so?

```YAML
---
master_plugins:
  - { plugin: gravityformscli, activate: true }
  - { plugin: iwp-client, activate: true }
  - { plugin: wordfence, activate: false }
  - { plugin: wp-sentry-integration, activate: false }
sites:

  example:
    repo: https://github.com/JPry/vvv-base.git
    hosts:
      - wp.example.co.uk
    custom:
      title: Example site
      db_prefix: ex_
      plugins:
        - { plugin: duplicate-post, activate: true }
        - { plugin: email-templates, activate: true }
        - { plugin: uk-cookie-consent, activate: true }
      locale: en_GB
      wp: true
```

**Comment by JPry** [comment]
Yes, it would be handled like that. I would probably want to use something more specific as a key, like `vvv_base_plugins`, but it would work the same way.

The provisioner would look for that value, store it, and then when handling the install process it would also include those from the master list.

**Comment by JPry** [comment]
This is now available on the `develop` branch. Details for how to use will be forthcoming, but here's an example:

```yaml
sites:

     #normal sets of site configs here.

vvvbase:
    db:
        host: localhost
        user: root
        pass: root

    # Works exactly the same as the plugins array in the main site config
    plugins:
        - jetpack

    # Works exactly the same as the themes array in the main site config
    themes:
        - twentyseventeen
```
