### ISSUE TITLE
Alternative to wp-content, one directory level up (i.e. htdocs)

### ISSUE THREAD

**Issue by salcode** [JPry/vvv-base#3]
First, this is a great tool - thank you.

While the `wp-content` option is great if your repo is based in `wp-content`, it can also be convenient to have your repository setup from the root of the project (e.g. `htdocs`).  This is particularly helpful when deploying a project via Git.

To this end, it would be nice to have an option that works just like the `wp-content` option except up a level.

**Comment by JPry** [comment]
@salcode great suggestion!

**Comment by JPry** [comment]
@salcode In this kind of setup, do you typically version all of the WP files, or just the portions you need?

**Comment by salcode** [comment]
In this setup, I usually only version:

- `.gitignore`
- a plugin or two (that are specific to the site)
- the theme

I usually use this [WordPress .gitignore file](https://salferrarello.com/wordpress-gitignore/).

**Comment by JPry** [comment]
I'll be testing how well WP CLI handles existing files when downloading WP. It looks like it will overwrite anything existing, but only at the file level. That would mean custom content *should* be safe, but I'd like to see how it plays out. 

I'll test with my own personal site and I may recruit you to test some of yours, if you're willing.

**Comment by salcode** [comment]
Sure thing 👍

**Comment by JPry** [comment]
The changes from #7 are now in `master`.

**Comment by salcode** [comment]
I'm trying to test the `htdocs` feature with the following config

```
  jpry:
    repo: https://github.com/JPry/vvv-base.git
    htdocs: https://github.com/salcode/example-project-w-gitignore.git
    hosts:
        - jpry.local
```

## Expected Behavior

- `/htdocs` is a clone of https://github.com/salcode/example-project-w-gitignore.git
- WordPress core files are installed inside `/htdocs`

## Actual Behavior

- WordPress core files are installed inside `/htdocs`
- the git repo is __not__ cloned

## Notes

I got the same behavior when I added `wp: false`

```
  jpry:
    repo: https://github.com/JPry/vvv-base.git
    wp: false
    htdocs: https://github.com/salcode/example-project-w-gitignore.git
    hosts:
        - jpry.local

```

**Comment by JPry** [comment]
@salcode The options need to be inside of the `custom` array. So your `vvv-custom.yml` should look like this:

```yaml
sites:
  jpry:
    repo: https://github.com/JPry/vvv-base.git
    hosts:
      - jpry.local
    custom:
      htdocs: https://github.com/salcode/example-project-w-gitignore.git
```
