### ISSUE TITLE
xip.io only works on default site

### ISSUE THREAD

**Issue by colin-marshall** [JPry/vvv-base#33]
@JPry thanks for this great base config. I am having trouble getting xip to work on a custom site. I followed your [guide](https://jeremypry.com/how-to-view-a-locally-developed-website-on-other-devices/) and as far I can tell I have Vagrant setup correctly because the default WordPress site (local.wordpress.dev) loads through xip. When I try to load any custom site with it, it just goes to the main vvv.dev page.

Here is a sample from my `vvv-custom.yml` file:

```yaml
mysite:
    repo: https://github.com/JPry/vvv-base.git
    hosts:
      - mysite.dev
    custom:
      admin_user: admin
      admin_password: password
      admin_email: email@gmail.com
      title: My Site
      db_prefix: wp_
      multisite: false
      xipio: true
      version: latest
      locale: en_US
      themes:
        - twentyseventeen
      delete_default_plugins: true
      delete_default_themes: true
      wp: true
```

I noticed that when I create/provision custom sites they don't create a `provision/vvv-hosts` file, and there is one for default site. Could that be the issue? Thanks!
