### ISSUE TITLE
htdocs from private repo fails

### ISSUE THREAD

**Issue by jeremymoore** [JPry/vvv-base#42]
I'm on VVV 2.5.1 and I've configured my site as follows

```
sites:
  custom-site:
    repo: https://github.com/sampleorg/vvv-base.git
    hosts:
      - local.sample-site.com
    custom:
      htdocs: https://github.com/sampleorg/some-private-repo.git
```

When I provision, I end up receiving this in console: 

```
default: provisioner: [INFO] Creating /srv/www/custom-site/log directory...
    default: provisioner: [INFO] Cloning [https://github.com/sampleorg/some-private-repo.git] into /srv/www/custom-site/htdocs...
    default: provisioner: [ERROR] The command "'git' 'clone' 'https://github.com/sampleorfg/some-private-repo.git' '/srv/www/custom-site/htdocs' '--recursive'" failed.  Exit Code: 128(Invalid e
xit argument)  Working directory: /srv/www/custom-site  Output: ================   Error Output: ================ Cloning into '/srv/www/custom-site/htdocs'... fatal: could not read Username for '
https://github.com': No such device or address
```

Similarly, using the `git@github.com` repo address fails but references the missing key. 

Does this work with private repos? Am I missing something in my configuration? 

Thanks
